spring:
  profiles:
    active: test
  application:
    name: rocketmq4-learning-consumer

server:
  port: 8080
  servlet:
    context-path: /rocketmq4-learning-consumer

pagehelper:
  supportMethodsArguments: true
  reasonable: false
  helperDialect: mysql
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.courage.rocketmq4.domain.po

